name: cs5242-proj
dependencies:
  - python=3.9.12
  - pip:
    - imagehash==4.2.1
    - imageio==2.22.2
    - matplotlib==3.6.0
    - numpy==1.23.4
    - opencv-python==4.6.0.66
    - pillow==9.2.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - sklearn==1.1.3
    - torch==1.12.1
    - torchtext==0.13.1
    - torchvision==0.13.1
